# docker-compose --file ./docker-compose.yml up --build --force-recreate
# docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)
version: '2'
services:
  web:
    tty: true
    stdin_open: true
    restart: always
    build: ./docker/apache
    ports:
      - "8082:80"
    volumes:
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/drupal.ini:/etc/php/7.0/cli/conf.d/drupal.ini
      - ./docker/php/drupal.ini:/etc/php/7.0/apache2/conf.d/drupal.ini
      - ./code:/var/www/html:rw
      - ./files:/var/www/html/sites/default/files:rw
    links:
      - db
    depends_on:
      - db
    working_dir: /var/www/html
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: d7
