version: '2'
services:
  web:
    tty: true
    stdin_open: true
    restart: always
    build: ./docker/apache
    expose:
      - "80"
      - "3307"
    ports:
      - "8082:80" # HTTP
      - "3307:3306" #MYSQL
    volumes:
#      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/nginx/drupal.conf:/etc/nginx/sites-enabled/drupal.conf
      - ./docker/misc/start.sh:/start.sh
      - ./docker/php/drupal.ini:/etc/php/7.0/cli/conf.d/drupal.ini
      - ./docker/php/drupal.ini:/etc/php/7.0/fpm/conf.d/drupal.ini
      - ./code:/var/www/drupal
    working_dir: /var/www/drupal